version: "3.9"

networks:
  gpstrack_api:
    name: gpstrack_api


services:
  gpstrack_api:
    build: ./backend/
    platform: linux/amd64
    volumes:
      - ./backend:/app:cached
    networks:
      - gpstrack_api
    depends_on:
      - gpstrack_redis

  gpstrack_frontend:
    build: ./frontend/
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - gpstrack_api

  wallets_api:
    build: ./wallets/
    platform: linux/amd64
    volumes:
      - ./wallets:/wallets:cached
    networks:
      - gpstrack_api

  gpstrack_apinginx:
    container_name: gpstrack_apinginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/ssl:/etc/nginx/ssl
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gpstrack_api
    networks:
      - gpstrack_api

  gpstrack_apidb:
    image: postgres:alpine
    container_name: gpstrack_apidb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: serghei
      POSTGRES_DB: gpstrack
      POSTGRES_PASSWORD: Sereoja
    networks:
      - gpstrack_api

  gpstrack_redis:
    container_name: gpstrack_redis
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - gpstrack_api
